development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monologue_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monologue_test
  pool: 5
  username: root
  password:
