Monologue.site_name        = "jipiboily"
Monologue.site_url        = "http://jipiboily.com"
Monologue.disqus_shortname = "jipiboily"
Monologue.meta_description = "This is my personal blog about Rails, Monologue, programming, etc..."
Monologue.meta_keyword     = "rails, programming, monologue, ruby"